version: '{branch}.{build}'
configuration: RelWithDebInfo
install:
- cinst -y swig
cache:
- C:\ProgramData\chocolatey\bin -> appveyor.yml
- C:\ProgramData\chocolatey\lib -> appveyor.yml
before_build:
- mkdir BLD
- cd BLD
- cmake -G "Visual Studio 12" -DBUILD_PERL=no  %QPID_PROTON_CMAKE_ARGS% ..
- cd ..
build:
  parallel: true
  verbosity: normal
test_script:
- cd BLD
- cmake --build . --target install --config %CONFIGURATION%
- ctest -V -C %CONFIGURATION% %QPID_PROTON_CTEST_ARGS%
- cd ..
